#!/bin/bash

################-> are comments
################-> "#PBS" are Batch Script commands

#PBS -m abe

################ Verbose mode

#PBS -V

################

################ Change these parameters according to your requisites

#PBS -l nodes=grad05:ppn=16:cluster-Grad,walltime=01:00:00

################ Where:
################ nodes = number of nodes requested
################ ppn = number of cores per node
################ cluster-Atlantica / cluster-Gates = cluster name
################ walltime = max allocation time

################ Please, change this e-mail address to yours

#PBS -M matheus.ferreira.001@acad.pucrs.br

################

#PBS -r n

################ Output options

#PBS -j oe

################

################ Please, change this directory to your working dir.

#PBS -d /home/pp12734/T1-prog-paralela/src

################

################
echo Running on host `hostname`
echo
echo Initial Time is `date`
echo
echo Directory is `pwd`
echo
echo This jobs runs on the following nodes:
echo `cat $PBS_NODEFILE | uniq`
echo
echo JOB_ID:
echo `echo $PBS_JOBID`
echo ################



############# If running a sequential or openMP program

./solution-par > dados-par.txt.1 2> tempos-par.txt.1
./solution-par > dados-par.txt.2 2> tempos-par.txt.2
./solution-par > dados-par.txt.3 2> tempos-par.txt.3

################

echo Final Time is `date`

